class ExamInfo {
  final String id;
  final String name;
  final String code;
  final String conductingBody;
  final String qualification;
  final int minAge;
  final int maxAgeGeneral;
  final int maxAgeOBC;
  final int maxAgeSC;
  final int maxAgeST;
  final int maxAttemptsGeneral;
  final int maxAttemptsOBC;
  final int maxAttemptsSCST;
  final String category;
  final String description;
  final String icon;
  final String registrationUrl;
  final String officialInfoUrl;

  const ExamInfo({
    required this.id,
    required this.name,
    required this.code,
    required this.conductingBody,
    required this.qualification,
    required this.minAge,
    required this.maxAgeGeneral,
    required this.maxAgeOBC,
    required this.maxAgeSC,
    required this.maxAgeST,
    required this.maxAttemptsGeneral,
    required this.maxAttemptsOBC,
    required this.maxAttemptsSCST,
    required this.category,
    required this.description,
    this.icon = '📝',
    this.registrationUrl = '',
    this.officialInfoUrl = '',
  });
}

class ExamData {
  static const List<ExamInfo> allExams = [
    ExamInfo(
      id: 'upsc_cse',
      name: 'UPSC Civil Services',
      code: 'UPSC CSE',
      conductingBody: 'Union Public Service Commission',
      qualification: 'Graduation (any stream)',
      minAge: 21,
      maxAgeGeneral: 32,
      maxAgeOBC: 35,
      maxAgeSC: 37,
      maxAgeST: 37,
      maxAttemptsGeneral: 6,
      maxAttemptsOBC: 9,
      maxAttemptsSCST: -1,
      category: 'UPSC',
      description: 'Premier civil services examination for IAS, IPS, IFS & more',
      icon: '🏛️',
      registrationUrl: 'https://upsconline.nic.in',
      officialInfoUrl: 'https://upsc.gov.in/examinations/civil-services-examination',
    ),
    ExamInfo(
      id: 'ssc_cgl',
      name: 'SSC CGL',
      code: 'SSC CGL',
      conductingBody: 'Staff Selection Commission',
      qualification: 'Graduation (any stream)',
      minAge: 18,
      maxAgeGeneral: 32,
      maxAgeOBC: 35,
      maxAgeSC: 37,
      maxAgeST: 37,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'SSC',
      description: 'Combined Graduate Level exam for Group B & C posts',
      icon: '📋',
      registrationUrl: 'https://ssc.gov.in',
      officialInfoUrl: 'https://ssc.gov.in',
    ),
    ExamInfo(
      id: 'ssc_chsl',
      name: 'SSC CHSL',
      code: 'SSC CHSL',
      conductingBody: 'Staff Selection Commission',
      qualification: '12th Pass',
      minAge: 18,
      maxAgeGeneral: 27,
      maxAgeOBC: 30,
      maxAgeSC: 32,
      maxAgeST: 32,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'SSC',
      description: 'Combined Higher Secondary Level for LDC, DEO, PA/SA posts',
      icon: '📝',
      registrationUrl: 'https://ssc.gov.in',
      officialInfoUrl: 'https://ssc.gov.in',
    ),
    ExamInfo(
      id: 'afcat',
      name: 'AFCAT',
      code: 'AFCAT',
      conductingBody: 'Indian Air Force',
      qualification: 'Graduation (min 60%)',
      minAge: 20,
      maxAgeGeneral: 24,
      maxAgeOBC: 24,
      maxAgeSC: 24,
      maxAgeST: 24,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Defence',
      description: 'Air Force Common Admission Test for Flying and Ground Duty',
      icon: '✈️',
      registrationUrl: 'https://afcat.cdac.in',
      officialInfoUrl: 'https://indianairforce.nic.in/content/afcat',
    ),
    ExamInfo(
      id: 'ibps_po',
      name: 'IBPS PO',
      code: 'IBPS PO',
      conductingBody: 'Institute of Banking Personnel Selection',
      qualification: 'Graduation (any stream)',
      minAge: 20,
      maxAgeGeneral: 30,
      maxAgeOBC: 33,
      maxAgeSC: 35,
      maxAgeST: 35,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Banking',
      description: 'Probationary Officer exam for public sector banks',
      icon: '🏦',
      registrationUrl: 'https://ibps.in',
      officialInfoUrl: 'https://ibps.in/crp-po-mt.html',
    ),
    ExamInfo(
      id: 'ibps_clerk',
      name: 'IBPS Clerk',
      code: 'IBPS Clerk',
      conductingBody: 'Institute of Banking Personnel Selection',
      qualification: 'Graduation (any stream)',
      minAge: 20,
      maxAgeGeneral: 28,
      maxAgeOBC: 31,
      maxAgeSC: 33,
      maxAgeST: 33,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Banking',
      description: 'Clerical cadre exam for public sector banks',
      icon: '🏦',
      registrationUrl: 'https://ibps.in',
      officialInfoUrl: 'https://ibps.in/crp-clerk.html',
    ),
    ExamInfo(
      id: 'sbi_po',
      name: 'SBI PO',
      code: 'SBI PO',
      conductingBody: 'State Bank of India',
      qualification: 'Graduation (any stream)',
      minAge: 21,
      maxAgeGeneral: 30,
      maxAgeOBC: 33,
      maxAgeSC: 35,
      maxAgeST: 35,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Banking',
      description: 'Probationary Officer exam for State Bank of India',
      icon: '🏦',
      registrationUrl: 'https://sbi.co.in/web/careers',
      officialInfoUrl: 'https://sbi.co.in/web/careers',
    ),
    ExamInfo(
      id: 'rbi_grade_b',
      name: 'RBI Grade B',
      code: 'RBI Gr.B',
      conductingBody: 'Reserve Bank of India',
      qualification: 'Graduation (min 60%)',
      minAge: 21,
      maxAgeGeneral: 30,
      maxAgeOBC: 33,
      maxAgeSC: 35,
      maxAgeST: 35,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Banking',
      description: 'Officer Grade B exam for Reserve Bank of India',
      icon: '🏛️',
      registrationUrl: 'https://opportunities.rbi.org.in',
      officialInfoUrl: 'https://rbi.org.in/Scripts/Vacancies.aspx',
    ),
    ExamInfo(
      id: 'nda',
      name: 'NDA',
      code: 'NDA',
      conductingBody: 'Union Public Service Commission',
      qualification: '12th Pass (PCM for Navy/AF)',
      minAge: 16,
      maxAgeGeneral: 18,
      maxAgeOBC: 18,
      maxAgeSC: 18,
      maxAgeST: 18,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Defence',
      description: 'National Defence Academy entrance for Army, Navy, Air Force',
      icon: '⚔️',
      registrationUrl: 'https://upsconline.nic.in',
      officialInfoUrl: 'https://upsc.gov.in/examinations/national-defence-academy-and-naval-academy-examination',
    ),
    ExamInfo(
      id: 'cds',
      name: 'CDS',
      code: 'CDS',
      conductingBody: 'Union Public Service Commission',
      qualification: 'Graduation',
      minAge: 19,
      maxAgeGeneral: 25,
      maxAgeOBC: 25,
      maxAgeSC: 25,
      maxAgeST: 25,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Defence',
      description: 'Combined Defence Services exam for OTA, IMA, INA, AFA',
      icon: '🎖️',
      registrationUrl: 'https://upsconline.nic.in',
      officialInfoUrl: 'https://upsc.gov.in/examinations/combined-defence-services-examination',
    ),
    ExamInfo(
      id: 'rrb_ntpc',
      name: 'RRB NTPC',
      code: 'RRB NTPC',
      conductingBody: 'Railway Recruitment Board',
      qualification: 'Graduation',
      minAge: 18,
      maxAgeGeneral: 33,
      maxAgeOBC: 36,
      maxAgeSC: 38,
      maxAgeST: 38,
      maxAttemptsGeneral: -1,
      maxAttemptsOBC: -1,
      maxAttemptsSCST: -1,
      category: 'Railways',
      description: 'Non-Technical Popular Categories exam for Indian Railways',
      icon: '🚂',
      registrationUrl: 'https://indianrailways.gov.in',
      officialInfoUrl: 'https://indianrailways.gov.in',
    ),
  ];

  // Mock upcoming deadlines
  static List<Map<String, dynamic>> get upcomingDeadlines => [
    {
      'examName': 'UPSC CSE 2026',
      'event': 'Application Deadline',
      'date': DateTime.now().add(const Duration(days: 5)),
      'urgency': 'high',
    },
    {
      'examName': 'SSC CGL 2026',
      'event': 'Exam Date',
      'date': DateTime.now().add(const Duration(days: 18)),
      'urgency': 'medium',
    },
    {
      'examName': 'IBPS PO 2026',
      'event': 'Notification Out',
      'date': DateTime.now().add(const Duration(days: 32)),
      'urgency': 'low',
    },
    {
      'examName': 'SBI PO 2026',
      'event': 'Application Start',
      'date': DateTime.now().add(const Duration(days: 45)),
      'urgency': 'low',
    },
    {
      'examName': 'RBI Grade B',
      'event': 'Application Deadline',
      'date': DateTime.now().add(const Duration(days: 12)),
      'urgency': 'medium',
    },
  ];

  // Mock timeline events
  static List<Map<String, dynamic>> get timelineEvents => [
    {
      'examName': 'UPSC CSE 2026',
      'event': 'Notification Released',
      'date': DateTime.now().subtract(const Duration(days: 30)),
      'completed': true,
      'type': 'notification',
    },
    {
      'examName': 'UPSC CSE 2026',
      'event': 'Application Window Open',
      'date': DateTime.now().subtract(const Duration(days: 20)),
      'completed': true,
      'type': 'application_start',
    },
    {
      'examName': 'SSC CGL 2026',
      'event': 'Notification Released',
      'date': DateTime.now().subtract(const Duration(days: 10)),
      'completed': true,
      'type': 'notification',
    },
    {
      'examName': 'UPSC CSE 2026',
      'event': 'Application Deadline',
      'date': DateTime.now().add(const Duration(days: 5)),
      'completed': false,
      'type': 'application_end',
    },
    {
      'examName': 'RBI Grade B',
      'event': 'Application Deadline',
      'date': DateTime.now().add(const Duration(days: 12)),
      'completed': false,
      'type': 'application_end',
    },
    {
      'examName': 'SSC CGL 2026',
      'event': 'Exam Date — Tier I',
      'date': DateTime.now().add(const Duration(days: 18)),
      'completed': false,
      'type': 'exam',
    },
    {
      'examName': 'IBPS PO 2026',
      'event': 'Notification Expected',
      'date': DateTime.now().add(const Duration(days: 32)),
      'completed': false,
      'type': 'notification',
    },
    {
      'examName': 'UPSC CSE 2026',
      'event': 'Prelims Exam',
      'date': DateTime.now().add(const Duration(days: 60)),
      'completed': false,
      'type': 'exam',
    },
  ];

  // Categories for filter chips
  static const List<String> examCategories = [
    'All',
    'UPSC',
    'SSC',
    'Banking',
    'Defence',
    'Railways',
    'State PSC',
  ];

  // User categories
  static const List<String> userCategories = [
    'General',
    'OBC',
    'SC',
    'ST',
    'EWS',
    'PwD',
  ];

  // Qualifications
  static const List<String> qualifications = [
    '10th Pass',
    '12th Pass',
    'Graduation',
    'Post Graduation',
    'PhD',
  ];
}
