/// Static data for Indian educational institutions — used in Profile dropdowns/pickers.
class IndiaData {
  IndiaData._();

  // ── All Indian School Boards (65+) ────────────────────────────────────────
  static const List<String> boards = [
    // Central Boards
    'CBSE — Central Board of Secondary Education',
    'CISCE — Council for the Indian School Certificate Examinations (ICSE)',
    'NIOS — National Institute of Open Schooling',
    // State Boards — Alphabetical
    'Andhra Pradesh Board of Secondary Education (BSEAP)',
    'Andhra Pradesh Board of Intermediate Education (BIEAP)',
    'Arunachal Pradesh Board of Secondary Education (APBSE)',
    'Assam Higher Secondary Education Council (AHSEC)',
    'Assam Secondary Education Board (SEBA)',
    'Assam State Open School (ASOS)',
    'Bihar School Examination Board (BSEB)',
    'Bihar Intermediate Education Council (BIEC)',
    'Chhattisgarh Board of Secondary Education (CGBSE)',
    'Goa Board of Secondary and Higher Secondary Education (GBSHSE)',
    'Gujarat Secondary and Higher Secondary Education Board (GSEB)',
    'Haryana Board of School Education (HBSE)',
    'Himachal Pradesh Board of School Education (HPBOSE)',
    'Jharkhand Academic Council (JAC)',
    'Karnataka Secondary Education Examination Board (KSEEB)',
    'Kerala Board of Higher Secondary Examination (BHSE)',
    'Kerala Board of Secondary Education (BSEK)',
    'Madhya Pradesh Board of Secondary Education (MPBSE)',
    'Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)',
    'Manipur Board of Secondary Education (MBSE)',
    'Manipur Council of Higher Secondary Education (MCHSE)',
    'Meghalaya Board of School Education (MBOSE)',
    'Mizoram Board of School Education (MBSE-Mizoram)',
    'Nagaland Board of School Education (NBSE)',
    'Odisha Board of Secondary Education (BSE Odisha)',
    'Council of Higher Secondary Education Odisha (CHSE Odisha)',
    'Punjab School Education Board (PSEB)',
    'Rajasthan Board of Secondary Education (RBSE)',
    'Rajasthan State Open School (RSOS)',
    'Sikkim Board of Secondary Education (SBSE)',
    'Tamil Nadu Board of Secondary Education (TNBSE)',
    'Tamil Nadu Higher Secondary Examinations (TNHSE)',
    'Telangana Board of Secondary Education (TBSE)',
    'Telangana Board of Intermediate Education (TBIE)',
    'Tripura Board of Secondary Education (TBSE-Tripura)',
    'Tripura Board of Higher Secondary Education (TBHSE)',
    'Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)',
    'UP Board of High School and Intermediate Education',
    'Uttarakhand Board of School Education (UBSE)',
    'West Bengal Board of Secondary Education (WBBSE)',
    'West Bengal Council of Higher Secondary Education (WBCHSE)',
    // UT Boards
    'Directorate of Education, Delhi (DELHI GOVT)',
    'Jammu and Kashmir Board of School Education (JKBOSE)',
    'Ladakh Board of School Education (LBoSE)',
    'Puducherry Board of Secondary Education',
    'Chandigarh Board of School Education (CBSE-Chandigarh)',
    'Directorate of School Education, Andaman and Nicobar Islands',
    'Directorate of Education, Dadra and Nagar Haveli',
    'Directorate of Education, Daman and Diu',
    'Directorate of Education, Lakshadweep',
    // Open / Distance Boards
    'Karnataka Open Educational Society (KSOS)',
    'Maharashtra State Open School (MSOS)',
    'Bihar State Open School (BSOS)',
    'Uttar Pradesh Rajarshi Tandon Open University (UPRTOU)',
    'Rajasthan State Open School (RSOS)',
    'Odisha State Open School (OSOS)',
    // Madrasa
    'Central Board of Madrasa Education',
    'State Madrasa Education Boards (various)',
    // Vedic / Sanskrit
    'Rashtriya Sanskrit Sansthan (RSS-Sanskrit)',
    // Others
    'Other (not listed)',
  ];

  // ── Short / Acronym-friendly list for search display ─────────────────────
  static const List<String> boardShortNames = [
    'CBSE', 'ICSE', 'ISC', 'NIOS',
    'BSEAP', 'BIEAP', 'APBSE', 'AHSEC', 'SEBA', 'ASOS',
    'BSEB', 'BIEC', 'CGBSE', 'GBSHSE', 'GSEB',
    'HBSE', 'HPBOSE', 'JAC', 'KSEEB',
    'BHSE Kerala', 'BSE Kerala', 'MPBSE', 'MSBSHSE',
    'MBSE', 'MCHSE', 'MBOSE', 'NBSE',
    'BSE Odisha', 'CHSE Odisha', 'PSEB', 'RBSE', 'RSOS',
    'SBSE', 'TNBSE', 'TBSE', 'TBIE', 'TBHSE',
    'UPMSP', 'UP Board', 'UBSE', 'WBBSE', 'WBCHSE',
    'JKBOSE', 'Puducherry Board',
  ];

  // ── UG Courses ────────────────────────────────────────────────────────────
  static const List<String> ugCourses = [
    // Engineering & Technology
    'B.Tech — Bachelor of Technology',
    'B.E. — Bachelor of Engineering',
    'B.Arch — Bachelor of Architecture',
    'B.Plan — Bachelor of Planning',
    // Science
    'B.Sc — Bachelor of Science',
    'B.Sc (Hons) — Bachelor of Science (Honours)',
    'B.Sc Agriculture',
    'B.Sc Nursing',
    'B.Sc Biotechnology',
    'B.Sc Computer Science',
    'B.Sc Physics',
    'B.Sc Chemistry',
    'B.Sc Mathematics',
    // Medical / Health
    'MBBS — Bachelor of Medicine and Surgery',
    'BDS — Bachelor of Dental Surgery',
    'BAMS — Bachelor of Ayurvedic Medicine and Surgery',
    'BHMS — Bachelor of Homeopathic Medicine and Surgery',
    'BUMS — Bachelor of Unani Medicine and Surgery',
    'B.Pharm — Bachelor of Pharmacy',
    'BPT — Bachelor of Physiotherapy',
    'BOT — Bachelor of Occupational Therapy',
    // Commerce
    'B.Com — Bachelor of Commerce',
    'B.Com (Hons) — Bachelor of Commerce (Honours)',
    'BBA — Bachelor of Business Administration',
    'BBM — Bachelor of Business Management',
    'BMS — Bachelor of Management Studies',
    'BCA — Bachelor of Computer Applications',
    'B.Fin — Bachelor of Finance',
    // Arts / Humanities
    'B.A. — Bachelor of Arts',
    'B.A. (Hons) — Bachelor of Arts (Honours)',
    'B.S.W. — Bachelor of Social Work',
    'B.F.A. — Bachelor of Fine Arts',
    'B.P.A. — Bachelor of Performing Arts',
    'B.Des — Bachelor of Design',
    'B.F.Tech — Bachelor of Fashion Technology',
    'B.J.M.C. — Bachelor of Journalism and Mass Communication',
    // Law
    'LLB — Bachelor of Laws (3 Year)',
    'BA LLB — Bachelor of Arts and Laws (5 Year)',
    'B.Com LLB — Bachelor of Commerce and Laws (5 Year)',
    'BBA LLB — Bachelor of Business Administration and Laws (5 Year)',
    // Education
    'B.Ed — Bachelor of Education',
    'D.El.Ed — Diploma in Elementary Education',
    'B.P.Ed — Bachelor of Physical Education',
    // Hotel / Hospitality
    'BHM — Bachelor of Hotel Management',
    'BTTM — Bachelor of Tourism and Travel Management',
    // Other
    'Integrated B.Tech-M.Tech (5 Year)',
    'Integrated BA-LLB (5 Year)',
    'Other UG Course',
  ];

  // ── PG Courses ────────────────────────────────────────────────────────────
  static const List<String> pgCourses = [
    'M.Tech — Master of Technology',
    'M.E. — Master of Engineering',
    'M.Arch — Master of Architecture',
    'M.Sc — Master of Science',
    'M.Sc (Hons)',
    'MBA — Master of Business Administration',
    'PGDM — Post Graduate Diploma in Management',
    'MCA — Master of Computer Applications',
    'M.Com — Master of Commerce',
    'M.A. — Master of Arts',
    'M.S.W. — Master of Social Work',
    'M.F.A. — Master of Fine Arts',
    'M.Des — Master of Design',
    'LLM — Master of Laws',
    'M.Ed — Master of Education',
    'M.Phil — Master of Philosophy',
    'MD — Doctor of Medicine',
    'MS — Master of Surgery',
    'M.D.S. — Master of Dental Surgery',
    'M.Pharm — Master of Pharmacy',
    'MPT — Master of Physiotherapy',
    'MHM — Master of Hotel Management',
    'MJM — Master of Journalism and Mass Communication',
    'MBA (Executive)',
    'MBA (HR)', 'MBA (Finance)', 'MBA (Marketing)', 'MBA (Operations)',
    'Other PG Course',
  ];

  // ── Combined list for picker display ──────────────────────────────────────
  static List<String> get allCourses => [...ugCourses, ...pgCourses];

  // ── Indian Universities (~200 key institutions — NIC/UGC listed) ──────────
  static const List<String> universities = [
    // IITs
    'IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur',
    'IIT Roorkee', 'IIT Guwahati', 'IIT Hyderabad', 'IIT Jodhpur', 'IIT Patna',
    'IIT Gandhinagar', 'IIT Indore', 'IIT Mandi', 'IIT Ropar', 'IIT Bhubaneswar',
    'IIT Varanasi (BHU)', 'IIT Palakkad', 'IIT Tirupati', 'IIT Dhanbad (ISM)',
    'IIT Jammu', 'IIT Goa', 'IIT Dharwad', 'IIT Bhilai',
    // NITs
    'NIT Trichy', 'NIT Warangal', 'NIT Surathkal', 'NIT Rourkela',
    'NIT Calicut', 'NIT Allahabad (MNNIT)', 'NIT Jaipur (MNIT)',
    'NIT Bhopal (MANIT)', 'NIT Kurukshetra', 'NIT Surat (SVNIT)',
    'NIT Patna', 'NIT Silchar', 'NIT Hamirpur', 'NIT Jalandhar',
    'NIT Meghalaya', 'NIT Nagaland', 'NIT Mizoram', 'NIT Manipur',
    'NIT Arunachal Pradesh', 'NIT Puducherry', 'NIT Goa', 'NIT Delhi',
    'NIT Uttarakhand', 'NIT Sikkim', 'NIT Agartala',
    // Central Universities
    'University of Delhi', 'Jawaharlal Nehru University (JNU)',
    'Banaras Hindu University (BHU)', 'Aligarh Muslim University (AMU)',
    'Hyderabad University', 'University of Allahabad',
    'Pondicherry University', 'Jamia Millia Islamia',
    'Central University of Punjab', 'Central University of Rajasthan',
    'Central University of Gujarat', 'Central University of Jharkhand',
    'Central University of Karnataka', 'Central University of Kerala',
    'Central University of Haryana', 'Central University of Himachal Pradesh',
    'Central University of Odisha', 'Central University of Tamil Nadu',
    'Central University of Kashmir', 'Central University of Jammu',
    'Central University of South Bihar', 'Dr. Hari Singh Gour University (Sagar)',
    'Guru Ghasidas Vishwavidyalaya (Bilaspur)', 'Hemvati Nandan Bahuguna Garhwal University',
    'Indira Gandhi National Tribal University (IGNTU)',
    'Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya (Wardha)',
    'Manipur University', 'Maulana Azad National Urdu University',
    'Mizoram University', 'Nagaland University',
    'North Eastern Hill University (NEHU)', 'Rajiv Gandhi University (Arunachal)',
    'Sikkim University', 'Tripura University', 'Tezpur University',
    'Visva-Bharati (Santiniketan)', 'IGNOU — Indira Gandhi National Open University',
    // IIMs
    'IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'IIM Lucknow',
    'IIM Kozhikode', 'IIM Indore', 'IIM Rohtak', 'IIM Ranchi',
    'IIM Raipur', 'IIM Udaipur', 'IIM Kashipur', 'IIM Trichy',
    'IIM Nagpur', 'IIM Visakhapatnam', 'IIM Amritsar', 'IIM Bodh Gaya',
    'IIM Sirmaur', 'IIM Jammu', 'IIM Sambalpur',
    // IISERs
    'IISER Pune', 'IISER Kolkata', 'IISER Mohali', 'IISER Bhopal', 'IISER Thiruvananthapuram',
    'IISER Tirupati', 'IISER Berhampur',
    // Other Premier
    'AIIMS Delhi', 'AIIMS Bhopal', 'AIIMS Jodhpur', 'AIIMS Patna', 'AIIMS Rishikesh',
    'IISc Bangalore',
    'BITS Pilani', 'BITS Goa', 'BITS Hyderabad',
    'VIT Vellore', 'VIT Chennai',
    'Manipal Academy of Higher Education',
    'Amity University', 'SRM Institute of Science and Technology',
    'Lovely Professional University (LPU)', 'Chandigarh University',
    'Christ University Bangalore',
    // State Universities — Major
    'University of Mumbai', 'Pune University (SPPU)',
    'Nagpur University (RTMNU)', 'University of Mysore',
    'Bangalore University', 'Karnataka University Dharwad',
    'Mangalore University', 'Gulbarga University',
    'Osmania University Hyderabad', 'Andhra University',
    'Sri Venkateswara University', 'University of Madras',
    'Anna University', 'Bharathidasan University', 'Alagappa University',
    'Madurai Kamaraj University', 'Annamalai University',
    'Calicut University', 'Kerala University', 'Mahatma Gandhi University (Kerala)',
    'Kannur University', 'Cochin University of Science and Technology (CUSAT)',
    'University of Calcutta', 'Jadavpur University',
    'Presidency University Kolkata', 'Kalyani University',
    'Burdwan University', 'Vidyasagar University',
    'North Bengal University', 'Rabindra Bharati University',
    'Delhi University (DU)', 'Amity University Delhi',
    'Guru Gobind Singh Indraprastha University (GGSIPU)',
    'Jamia Hamdard', 'Netaji Subhas University of Technology (NSUT)',
    'Chandigarh University', 'Panjab University Chandigarh',
    'Punjab Technical University (PTU)', 'Guru Nanak Dev University',
    'Kurukshetra University', 'Maharshi Dayanand University (MDU)',
    'Chaudhary Charan Singh University (CCS)', 'Agra University (DBRAU)',
    'Lucknow University', 'Allahabad University', 'CSJM University Kanpur',
    'Chhatrapati Shahu Ji Maharaj University', 'MG Kashi Vidyapith',
    'Veer Bahadur Singh Purvanchal University', 'Mahatma Jyotiba Phule Rohilkhand University',
    'Rajasthan University', 'Rajasthan Technical University',
    'JNV University Jodhpur', 'MLS University Udaipur',
    'Gujarat University', 'Saurashtra University', 'MS University Vadodara',
    'Sardar Patel University', 'Veer Narmad South Gujarat University',
    'Patel University', 'Dr. Babasaheb Ambedkar Open University',
    'Madhya Pradesh Bhoj Open University',
    'DAVV Indore', 'Jiwaji University Gwalior', 'Awadhesh Pratap Singh University',
    'Barkatullah University Bhopal', 'Rani Durgavati University Jabalpur',
    'Bikaner Technical University', 'Shekhawati University',
    'Utkal University Odisha', 'Berhampur University', 'Sambalpur University',
    'Ravenshaw University', 'North Orissa University',
    'Gauhati University', 'Dibrugarh University', 'Tezpur University',
    'Cotton University', 'Assam University',
    'University of Patna', 'Magadh University', 'Tilka Manjhi Bhagalpur University',
    'Lalit Narayan Mithila University', 'Veer Kunwar Singh University',
    'Ranchi University', 'Vinoba Bhave University', 'Kolhan University',
    'Nilamber-Pitamber University', 'Sido Kanhu Murmu University',
    'Chaudhary Bansi Lal University', 'Indira Gandhi University Meerpur',
    'Munger University', 'Purnia University',
    'Hemchand Yadav University', 'Shahdol University Madhya Pradesh',
    'Sardar Patel University Gujarat', 'Krantiguru Shyamji Krishna Verma Kutch University',
    'Dr. Subhash University', 'Marwadi University',
    'Other (not listed)',
  ];
}
